In [56]:
library(DBI)
library(RPostgres)
library(tidyverse)
library(glue)
library(httr)
library(jsonlite)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)
library(ggplot2)
library(readr)

source("pitcher_profile_functions.r")
source("data_extract_functions.r")


pitcher_id <- 669373
pitcher_scouting_report_df <- pull_pitcher_scouting_report_from_database(pitcher_id)

# grab specific pitch type above 10% usage

pitcher_pitch_arsenal <- create_pitcher_pitch_arsenal(pitcher_scouting_report_df)

pitcher_statcast_df <- pull_pitcher_statcast_data_from_csv(pitcher_id, pitcher_pitch_arsenal)

pitcher_pitch_usage_df <- create_pitcher_pitch_usage_df(pitcher_statcast_df)

     pitcher_id pitcher_name  situation_id balls strikes stance runners_on
1    669373     Skubal, Tarik 1            0     0       R      FALSE
2    669373     Skubal, Tarik 1            0     0       R      FALSE
3    669373     Skubal, Tarik 1            0     0       R      FALSE
4    669373     Skubal, Tarik 1            0     0       R      FALSE
5    669373     Skubal, Tarik 2            0     1       R      FALSE
6    669373     Skubal, Tarik 2            0     1       R      FALSE
7    669373     Skubal, Tarik 2            0     1       R      FALSE
8    669373     Skubal, Tarik 2            0     1       R      FALSE
9    669373     Skubal, Tarik 3            0     1       R      FALSE
10   669373     Skubal, Tarik 3            0     1       R      FALSE
11   669373     Skubal, Tarik 3            0     1       R      FALSE
12   669373     Skubal, Tarik 3            0     1       R      FALSE
13   669373     Skubal, Tarik 4            0     1       R      FALSE
14   669373     Skubal, Tarik 4            0     1       R      FALSE
15   669373     Skubal, Tarik 4            0     1       R      FALSE
16   669373     Skubal, Tarik 4            0     1       R      FALSE
17   669373     Skubal, Tarik 5            0     1       R      FALSE
18   669373     Skubal, Tarik 5            0     1       R      FALSE
19   669373     Skubal, Tarik 5            0     1       R      FALSE
20   669373     Skubal, Tarik 5            0     1       R      FALSE
21   669373     Skubal, Tarik 6            0     2       R      FALSE
22   669373     Skubal, Tarik 6            0     2       R      FALSE
23   669373     Skubal, Tarik 6            0     2       R      FALSE
24   669373     Skubal, Tarik 6            0     2       R      FALSE
25   669373     Skubal, Tarik 7            0     2       R      FALSE
26   669373     Skubal, Tarik 7            0     2       R      FALSE
27   669373     Skubal, Tarik 7            0     2       R      FALSE
28   669373     Skubal, Tarik 7            0     2       R      FALSE
29   669373     Skubal, Tarik 8            0     2       R      FALSE
30   669373     Skubal, Tarik 8            0     2       R      FALSE
⋮    ⋮          ⋮             ⋮            ⋮     ⋮       ⋮      ⋮
3283 669373     Skubal, Tarik 821          3     2       L      TRUE
3284 669373     Skubal, Tarik 821          3     2       L      TRUE
3285 669373     Skubal, Tarik 822          3     2       L      TRUE
3286 669373     Skubal, Tarik 822          3     2       L      TRUE
3287 669373     Skubal, Tarik 822          3     2       L      TRUE
3288 669373     Skubal, Tarik 822          3     2       L      TRUE
3289 669373     Skubal, Tarik 823          3     2       L      TRUE
3290 669373     Skubal, Tarik 823          3     2       L      TRUE
3291 669373     Skubal, Tarik 823          3     2       L      TRUE
3292 669373     Skubal, Tarik 823          3     2       L      TRUE
3293 669373     Skubal, Tarik 824          3     2       L      TRUE
3294 669373     Skubal, Tarik 824          3     2       L      TRUE
3295 669373     Skubal, Tarik 824          3     2       L      TRUE
3296 669373     Skubal, Tarik 824          3     2       L      TRUE
3297 669373     Skubal, Tarik 825          3     2       L      TRUE
3298 669373     Skubal, Tarik 825          3     2       L      TRUE
3299 669373     Skubal, Tarik 825          3     2       L      TRUE
3300 669373     Skubal, Tarik 825          3     2       L      TRUE
3301 669373     Skubal, Tarik 826          3     2       L      TRUE
3302 669373     Skubal, Tarik 826          3     2       L      TRUE
3303 669373     Skubal, Tarik 826          3     2       L      TRUE
3304 669373     Skubal, Tarik 826          3     2       L      TRUE
3305 669373     Skubal, Tarik 827          3     2       L      TRUE
3306 669373     Skubal, Tarik 827          3     2       L      TRUE
3307 669373     Skubal, Tarik 827          3     2       L      TRUE
3308 669373     Skubal, Tarik 827          3     2       L      TRUE
3309 669373     Skubal, Tarik 828          3     2       L      TRUE
3310 669373     Skubal, Tarik 828          3     2       L      TRUE
3311 669373     Skubal, Tarik 828          3     2       L      TRUE
3312 669373     Skubal, Tarik 828          3     2       L      TRUE
     risp  tto count_leverage prev_pitch_type prev_pitch_name prev_result
1    FALSE 1   even           NA              NA              NA
2    FALSE 1   even           NA              NA              NA
3    FALSE 1   even           NA              NA              NA
4    FALSE 1   even           NA              NA              NA
5    FALSE 1   ahead          FF              4-Seam Fastball S
6    FALSE 1   ahead          FF              4-Seam Fastball S
7    FALSE 1   ahead          FF              4-Seam Fastball S
8    FALSE 1   ahead          FF              4-Seam Fastball S
9    FALSE 1   ahead          SL              Slider          S
10   FALSE 1   ahead          SL              Slider          S
11   FALSE 1   ahead          SL              Slider          S
12   FALSE 1   ahead          SL              Slider          S
13   FALSE 1   ahead          CH              Changeup        S
14   FALSE 1   ahead          CH              Changeup        S
15   FALSE 1   ahead          CH              Changeup        S
16   FALSE 1   ahead          CH              Changeup        S
17   FALSE 1   ahead          SI              Sinker          S
18   FALSE 1   ahead          SI              Sinker          S
19   FALSE 1   ahead          SI              Sinker          S
20   FALSE 1   ahead          SI              Sinker          S
21   FALSE 1   ahead          FF              4-Seam Fastball S
22   FALSE 1   ahead          FF              4-Seam Fastball S
23   FALSE 1   ahead          FF              4-Seam Fastball S
24   FALSE 1   ahead          FF              4-Seam Fastball S
25   FALSE 1   ahead          SL              Slider          S
26   FALSE 1   ahead          SL              Slider          S
27   FALSE 1   ahead          SL              Slider          S
28   FALSE 1   ahead          SL              Slider          S
29   FALSE 1   ahead          CH              Changeup        S
30   FALSE 1   ahead          CH              Changeup        S
⋮    ⋮     ⋮   ⋮              ⋮               ⋮               ⋮
3283 TRUE  2   even           FF              4-Seam Fastball B
3284 TRUE  2   even           FF              4-Seam Fastball B
3285 TRUE  2   even           FF              4-Seam Fastball S
3286 TRUE  2   even           FF              4-Seam Fastball S
3287 TRUE  2   even           FF              4-Seam Fastball S
3288 TRUE  2   even           FF              4-Seam Fastball S
3289 TRUE  2   even           SL              Slider          B
3290 TRUE  2   even           SL              Slider          B
3291 TRUE  2   even           SL              Slider          B
3292 TRUE  2   even           SL              Slider          B
3293 TRUE  2   even           SL              Slider          S
3294 TRUE  2   even           SL              Slider          S
3295 TRUE  2   even           SL              Slider          S
3296 TRUE  2   even           SL              Slider          S
3297 TRUE  2   even           CH              Changeup        B
3298 TRUE  2   even           CH              Changeup        B
3299 TRUE  2   even           CH              Changeup        B
3300 TRUE  2   even           CH              Changeup        B
3301 TRUE  2   even           CH              Changeup        S
3302 TRUE  2   even           CH              Changeup        S
3303 TRUE  2   even           CH              Changeup        S
3304 TRUE  2   even           CH              Changeup        S
3305 TRUE  2   even           SI              Sinker          B
3306 TRUE  2   even           SI              Sinker          B
3307 TRUE  2   even           SI              Sinker          B
3308 TRUE  2   even           SI              Sinker          B
3309 TRUE  2   even           SI              Sinker          S
3310 TRUE  2   even           SI              Sinker          S
3311 TRUE  2   even           SI              Sinker          S
3312 TRUE  2   even           SI              Sinker          S
     pitch_type pitch_name      probability
1    CH         Changeup        17.42
2    FF         4-Seam Fastball 49.83
3    SI         Sinker          16.57
4    SL         Slider          16.18
5    CH         Changeup        46.12
6    FF         4-Seam Fastball 35.57
7    SI         Sinker          10.02
8    SL         Slider           8.29
9    CH         Changeup        53.59
10   FF         4-Seam Fastball 25.98
11   SI         Sinker          12.58
12   SL         Slider           7.85
13   CH         Changeup        53.51
14   FF         4-Seam Fastball 34.72
15   SI         Sinker           8.60
16   SL         Slider           3.17
17   CH         Changeup        43.71
18   FF         4-Seam Fastball 30.14
19   SI         Sinker          16.45
20   SL         Slider           9.70
21   CH         Changeup        42.81
22   FF         4-Seam Fastball 45.73
23   SI         Sinker           4.79
24   SL         Slider           6.66
25   CH         Changeup        52.10
26   FF         4-Seam Fastball 34.98
27   SI         Sinker           6.31
28   SL         Slider           6.60
29   CH         Changeup        49.19
30   FF         4-Seam Fastball 44.21
⋮    ⋮          ⋮               ⋮
3283 SI         Sinker          36.66
3284 SL         Slider          24.23
3285 CH         Changeup        22.37
3286 FF         4-Seam Fastball 21.35
3287 SI         Sinker          33.90
3288 SL         Slider          22.38
3289 CH         Changeup        22.02
3290 FF         4-Seam Fastball 13.04
3291 SI         Sinker          43.35
3292 SL         Slider          21.58
3293 CH         Changeup        24.67
3294 FF         4-Seam Fastball 14.80
3295 SI         Sinker          40.43
3296 SL         Slider          20.10
3297 CH         Changeup        28.28
3298 FF         4-Seam Fastball 22.42
3299 SI         Sinker          38.09
3300 SL         Slider          11.21
3301 CH         Changeup        30.73
3302 FF         4-Seam Fastball 24.68
3303 SI         Sinker          34.46
3304 SL         Slider          10.12
3305 CH         Changeup        15.43
3306 FF         4-Seam Fastball 12.99
3307 SI         Sinker          48.66
3308 SL         Slider          22.93
3309 CH         Changeup        17.50
3310 FF         4-Seam Fastball 14.93
3311 SI         Sinker          45.95
3312 SL         Slider          21.62

In [76]:
source("pitcher_profile_functions.r")
source("data_extract_functions.r")

pitcher_pitch_characteristics_df <- create_pitcher_pitch_characteristics_df(pitcher_statcast_df)
pitcher_pitch_characteristics_df

  pitch_type pitch_name      avg_velo avg_rel_x avg_rel_y avg_rel_z avg_hmov
1 CH         Changeup        87.97    1.90      54.09     6.07       1.24
2 FF         4-Seam Fastball 97.54    1.59      54.05     6.23       0.29
3 SI         Sinker          97.30    1.69      54.01     6.13       1.10
4 SL         Slider          90.11    1.95      54.03     6.07      -0.27
  avg_vmov avg_vx0 avg_vy0 avg_vz0 avg_ax avg_ay avg_az avg_spin
1 0.52     -6.21   -127.87 -5.36   14.86  26.97  -25.50 1834.755
2 1.43     -4.98   -141.83 -6.69    5.05  32.91  -11.58 2356.345
3 1.12     -7.60   -141.39 -6.44   16.45  32.38  -15.84 2248.622
4 0.39     -4.53   -131.18 -4.49   -2.22  26.05  -26.93 2240.862

[1] "FF"